// packages/core/scripts/build-lib.ts
import path from 'node:path';
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import { spawn } from 'node:child_process';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '../../..');

const CODEPOINTS_LOCK = path.join(ROOT, 'packages/font/codepoints.lock.json');
const SRC_DATA = path.join(__dirname, '../src/icons-data.ts');
const DIST_DIR = path.join(__dirname, '../dist');
const DIST_ICONS_JSON = path.join(DIST_DIR, 'icons.json');

interface IconRecord {
  name: string;
  codepoint: number;
  unicode: string;
  isVariant: boolean;
}

const buildManifest = (): IconRecord[] => {
  if (!fs.existsSync(CODEPOINTS_LOCK)) {
    throw new Error(
      `Codepoints lockfile not found at ${CODEPOINTS_LOCK}. ` +
        `Run \`pnpm -F devicons build\` first to generate it, or ensure ` +
        `the font build runs before core-lib in build-all.ts.`,
    );
  }
  const raw: Record<string, number> = JSON.parse(
    fs.readFileSync(CODEPOINTS_LOCK, 'utf-8'),
  );
  return Object.entries(raw)
    .map(([name, codepoint]) => ({
      name,
      codepoint,
      unicode: String.fromCodePoint(codepoint),
      isVariant: name.endsWith('-icon'),
    }))
    .sort((a, b) => a.codepoint - b.codepoint);
};

const writeIconsData = (manifest: IconRecord[]) => {
  // Generated TS module — imported by src/index.ts at compile time.
  // Gitignored. Regenerated on every build.
  const body =
    '// AUTO-GENERATED by packages/core/scripts/build-lib.ts. Do not edit.\n' +
    "import type { IconRecord } from './index';\n\n" +
    'export const ICONS_DATA: readonly IconRecord[] = ' +
    JSON.stringify(manifest, null, 2) +
    ';\n';
  fs.writeFileSync(SRC_DATA, body);
};

const writeDistIconsJson = (manifest: IconRecord[]) => {
  fs.mkdirSync(DIST_DIR, { recursive: true });
  fs.writeFileSync(DIST_ICONS_JSON, JSON.stringify(manifest, null, 2) + '\n');
};

const runTsup = () =>
  new Promise<void>((resolve, reject) => {
    const child = spawn('pnpm', ['exec', 'tsup'], {
      cwd: path.resolve(__dirname, '..'),
      stdio: 'inherit',
    });
    child.on('exit', (code) =>
      code === 0
        ? resolve()
        : reject(new Error(`tsup exited with code ${code}`)),
    );
  });

export const buildLib = async () => {
  const manifest = buildManifest();
  writeIconsData(manifest);
  writeDistIconsJson(manifest);
  await runTsup();
};

// CLI entry: `tsx scripts/build-lib.ts`
if (import.meta.url === `file://${process.argv[1]}`) {
  buildLib().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
